### ISSUE TITLE
Benchmark between Pux and nikic/fast-route?

### ISSUE THREAD

**Issue by nhymxu** [c9s/Pux#100]
Anyone have benchmark between two route library?

**Comment by c9s** [comment]
https://github.com/tyler-sommer/php-router-benchmark/
<https://github.com/tyler-sommer/php-router-benchmark/blob/master/README.md>




<https://github.com/tyler-sommer/php-router-benchmark/blob/master/README.md>
Dũng Nguyễn <notifications@github.com> 於 2015年10月17日 星期六寫道：

**Comment by nhymxu** [comment]
I don't see  pure PHP implementation of Pux result?
because shared hosting can't install extension.

Thanks you!

**Comment by c9s** [comment]
Sorry, I don't have that. But I think it might be slower than FastRoute if you only use PHP implementation.

**Comment by nhymxu** [comment]
thanks you.
