### ISSUE TITLE
Symfony 2 Routing test

### ISSUE THREAD

**Issue by giorrrgio** [c9s/Pux#12]
Just to fully understand and replicate your benchmark, don't you think it would be fair to include the code you've used to test the Symfony Routing component?
For example, did you enable the cache_dir for the Symfony Routing component before running the tests?
https://symfony2-document.readthedocs.org/en/latest/components/routing.html#the-all-in-one-router

Thanks!

**Comment by c9s** [comment]
Hi all, 

Here is the updated benchmark result with php-r3 extension: 
https://github.com/c9s/php-router-benchmark

I am closing this issue since it's included in tyler's php-router-benchmark repo.
