### ISSUE TITLE
Add Pux pure PHP to the benchmark information

### ISSUE THREAD

**Issue by rk** [c9s/Pux#17]
I hate to say it, but comparing a C extension to a pure PHP implementation is like comparing a racehorse against a donkey. Especially for something like this. So saying the extension is faster than the Symphony router isn't saying much.

Personally, I'd like to know where the pure PHP implementation of Pux stands in relation to the extension, as well as other libraries.

**Comment by c9s** [comment]
Also added php-r3 to php-router-benchmark repo. I am waiting the PR to be merged :) 
https://github.com/c9s/php-router-benchmark

I am closing this issue since it's included in tyler's php-router-benchmark repo.
