### ISSUE TITLE
Typed Function Calls

### ISSUE THREAD

**Issue by apfritts** [c9s/Pux#70]
Hi!

We're interested in adding typed function calls to Pux and contributing them back to the project. Taking this example from the docs:

``` php
$mux->get('/product/:id', ['ProductController','itemAction'] , [
    'require' => [ 'id' => '\d+', ],
    'default' => [ 'id' => '1', ]
]);
```

would become:

``` php
$mux->get('/product/:id', ['ProductController','itemAction'] , [
    'require' => [ 'id' => Pux\Mux::TYPE_INTEGER, ],
    'default' => [ 'id' => '1', ]
]);
```

This would automatically match against \d+ and result in a call to as ProductionController()->itemAction( (int) $id) instead of passing a string type.

Why?

This will simplify controller logic and allow invalid input to be sent to a 404 page instead of through controller logic.

It also allows folks to start converting over to Hack / HHVM for other performance gains.

Any concerns over this feature? Will this have any impact on the C extension (which we don't use so I wouldn't be adding any code in).

**Comment by c9s** [comment]
Hi @apfritts 

Sorry I think I missed the mail. overall, I like this proposal, PRs will be welcomed. And yes, it will impact the C extension since the API is slightly different, but that's fine, we can add the C implementation later.

**Comment by c9s** [comment]
I like this type constraint idea, do you have any updates? just a friendly ping. :)

**Comment by apfritts** [comment]
Closing this out. I don't work in PHP and ... this has been open for far too long... sorry team!
