### ISSUE TITLE
Best way to benchmark my controller methods

### ISSUE THREAD

**Issue by oytuntez** [c9s/Pux#73]
Hi everybody,

Thanks a lot for putting this amazing router together! We are starting to use this on production, hopefully everything is going to be smooth.

I have a question. In development mode, we try to benchmark our controllers' methods. We are using https://github.com/nshahzad/codon-profiler for this purpose. My question is:

Is there a way for us to hook into dispatcher and possible run a closure before and after the route execution? So that we can gather memory and time data before and after the controller and provide a performance result.

Otherwise we will be putting these measures before and after Pux\Executor::execute() method. Do you think this is fine and does not add a lot between our execute() call and the actual method call inside the controller?

Thanks again for this package.

**Comment by c9s** [comment]
Hi @oytuntez,

Currently we don't have support to trigger callback before and after the route execution, but I remember we have a todo list for that.  for now you have to wrap the profiler method around the execute method and I think this is fine. :)

**Comment by oytuntez** [comment]
Sounds good @c9s! I will try to push a PR if I get to add callbacks and hooks in Pux.

**Comment by c9s** [comment]
By the way, can you propose the API before you make changes? so we can see what's look like when using it. Thanks!

**Comment by c9s** [comment]
And If your profile code is specific, you can simply wrap the execute method in your application.

**Comment by c9s** [comment]
Hi @oytuntez,

This can be done by wrapping your application logics with the new middleware design. please checkout 2.0 branch for more details

I will issue an update for you when 2.0 is ready to be released. Thanks.

**Comment by c9s** [comment]
HI @oytuntez  please see the related commit 8436dc2, which takes xhprof as an example.

**Comment by oytuntez** [comment]
@c9s, thank you so much for the update and for keeping in touch! I will try to upgrade our application to 2.0 as soon as possible.

**Comment by c9s** [comment]
@oytuntez The changelog was updated too. will notify you when the related doc is ready. https://github.com/c9s/Pux/blob/2.0/CHANGES.md

**Comment by oytuntez** [comment]
This version will make me remove a good amount of code from my base with middlewares! :)

**Comment by c9s** [comment]
glad you like it! there is a compositor for compositing middlewares and the application: https://github.com/c9s/Pux/blob/2.0/tests/Pux/CompositorTest.php
